/**
 * KAR-02.9 — the plan-hash golden.
 *
 * This is the cross-version stability test: `sha256Hex(canonicalJson(...))`
 * over a fixture covering all seven `PlanNode` types is compared to a
 * committed golden hex string. If a refactor of the canonical encoder ever
 * changes this value, every `plan` row in every existing ledger has just
 * been orphaned — that is a migration, never a snapshot update. See
 * docs/delivery/epics/EPIC-02-domain-model.md, KAR-02.9 "Notes / risks".
 *
 * The golden moved exactly once, in KAR-02.3, and the reason is recorded here
 * so nobody has to reconstruct it from `git log`: the fixture was written
 * before `PlanGraphSchema` existed and did not describe a legal graph — its
 * `loop` node carried `until`/`maxIterations` and its `subgraph` node a
 * `planRef`, none of which are fields in docs/04-domain-model.md §3.2, and
 * its `planHash` was a placeholder of 61 zeros where `PlanHashSchema` wants
 * 64 hex characters. Correcting the fixture changed the encoder's *input*.
 * The encoder itself is untouched, and no ledger existed to orphan. A future
 * diff here with the fixture unchanged is the migration the note above means.
 *
 * The second test below is what makes that distinction checkable rather than
 * asserted: it pins the encoder against a literal that lives in this file and
 * is never edited, so an encoder change shows up even when a fixture moves.
 *
 * Verifies: EPIC-02-S8 (golden-hash scenario) · AC1
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { expect, it, describe as suite } from 'vitest';
import { canonicalJson } from '../src/canonical-json.ts';
import { sha256Hex } from '../src/hash.ts';

const fixturePath = fileURLToPath(new URL('./fixtures/plans/seven-types.json', import.meta.url));
const planFixture: unknown = JSON.parse(readFileSync(fixturePath, 'utf8'));

suite('plan hash — golden', () => {
  it('sha256Hex(canonicalJson(planFixture)) matches the committed golden', async () => {
    const hex = await sha256Hex(canonicalJson(planFixture));
    await expect(hex).toMatchFileSnapshot('__snapshots__/plan-hash.golden');
  });

  it('encodes a fixed literal to a byte string whose digest was computed outside this repo', async () => {
    // Not a snapshot: an inline literal cannot be regenerated by `-u`. Both
    // values were derived independently of ./src — the canonical form by
    // reading the rules in docs/04-domain-model.md §3 (keys sorted at every
    // depth, no whitespace, `undefined` omitted, no Unicode normalisation),
    // the digest by hashing those bytes with a different sha256
    // implementation. If either assertion below fails, the encoder moved.
    const value = { b: null, a: [1, { z: 'ü', y: true }], '': 0 };
    expect(canonicalJson(value)).toBe('{"":0,"a":[1,{"y":true,"z":"ü"}],"b":null}');
    await expect(sha256Hex(canonicalJson(value))).resolves.toBe(
      'd37bad19b0507cb37dfc78b8fa1d26d26195a7f4bfcf83afb31d9e1a413eef82',
    );
  });
});
