/**
 * KAR-18.9 AC6 / EPIC-18-S62 — the `--json` documents do not change:
 * presentation, not contract.
 *
 * `--json` is what CI branches on (KAR-18.4 AC10, KAR-18.3 AC7), so a
 * presentation story that changes it is not a presentation story. The four
 * files under `__goldens__/` were captured from the renderers **before** this
 * story touched them and are never regenerated by this spec — a golden a test
 * can rewrite is a diary, not an assertion.
 *
 * The goldens are taken over fixed synthetic reports rather than over this
 * machine, and that is the point rather than a compromise: a golden captured
 * from a laptop's real `doctor` would encode that laptop's git version, and the
 * first CI run would "fix" it. What AC6 protects is the document — keys, order,
 * nesting, framing — which is a property of the renderer over a known report.
 * The real commands are then driven end to end and asserted to produce the same
 * *shape*, so the fixture path and the shipped path cannot drift apart.
 *
 * Verifies: EPIC-18-S62 · AC6 · test plan #5
 */
import { makeTempDir, removeTempDir, TestClock } from '@DeFlow/testkit';
import { readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, expect, it, describe as suite } from 'vitest';
import { reduceReport, renderJson } from '../../src/doctor/report.ts';
import { runDoctor } from '../../src/doctor/run.ts';
import { createRenderer } from '../../src/run/render.ts';
import { renderStatusJson, runStatus } from '../../src/status.ts';
import { doctorEnv } from './support/doctor-fixture.ts';
import {
  GOLDEN_DOCTOR_SECTIONS,
  GOLDEN_RUN,
  GOLDEN_STATUS,
  GOLDEN_STREAM,
} from './support/json-fixtures.ts';

const GOLDENS = fileURLToPath(new URL('./__goldens__/', import.meta.url));
const golden = (name: string): string => readFileSync(join(GOLDENS, name), 'utf8');

/** The ESC no machine-readable document may carry. */
const ESC = '\u001B';

let tmp = '';

beforeEach(async () => {
  tmp = await makeTempDir();
});

afterEach(async () => {
  await removeTempDir(tmp);
});

/** Every key path in a JSON value, in document order — the shape a consumer
 * indexes into, independent of the values a machine happened to produce. */
function keyPaths(value: unknown, prefix = ''): string[] {
  if (Array.isArray(value)) return value.flatMap((entry) => keyPaths(entry, `${prefix}[]`));
  if (typeof value !== 'object' || value === null) return [];
  return Object.entries(value).flatMap(([key, entry]) => [
    `${prefix}.${key}`,
    ...keyPaths(entry, `${prefix}.${key}`),
  ]);
}

suite('EPIC-18-S62 — byte-for-byte against a golden captured before the change', () => {
  it('doctor --json is the document it was', () => {
    const rendered = renderJson(reduceReport(GOLDEN_DOCTOR_SECTIONS));

    expect(rendered).toBe(golden('doctor.golden.json'));
    expect(rendered).not.toContain(ESC);
    expect(rendered).not.toContain('next:');
    expect(rendered).not.toContain('overall:');
  });

  it('status --json is the document it was', () => {
    const rendered = renderStatusJson(GOLDEN_STATUS);

    expect(rendered).toBe(golden('status.golden.json'));
    expect(rendered).not.toContain(ESC);
    expect(rendered).not.toContain('next:');
  });

  it('run --json is the NDJSON stream it was, line framing included', () => {
    const renderer = createRenderer({ mode: 'json', isTty: () => true, runId: GOLDEN_RUN });
    const rendered = GOLDEN_STREAM.map((event) => renderer.event(event)).join('');

    // "byte-identical" includes the framing: one object per line, and the
    // trailing newline a `while read line` depends on.
    expect(rendered).toBe(golden('run.golden.ndjson'));
    expect(rendered).not.toContain(ESC);
    expect(rendered.endsWith('\n')).toBe(true);
  });

  it("run --json's verdict line is the object it was, still on stderr", () => {
    const renderer = createRenderer({ mode: 'json', isTty: () => true, runId: GOLDEN_RUN });
    const final = renderer.final(
      { terminal: true, exitCode: 0, reason: 'completed — every gate passed' },
      {
        costUsd: { subscription: null, apiKey: 0.42, vendorReported: 0.42, estimated: null },
        wallclockMs: 3210,
      },
    );

    expect(final.stdout).toBe('');
    expect(final.stderr).toBe(golden('run-verdict.golden.json'));
  });
});

suite('the shipped path produces the same shape as the golden (AC6)', () => {
  it('a real doctor --json has the golden document, key for key', async () => {
    const dataDir = join(tmp, 'doctor-data');
    const cwd = join(tmp, 'repo');
    await mkdir(cwd, { recursive: true });

    const result = await runDoctor({
      cwd,
      env: doctorEnv({ dataDir, realGit: true }),
      clock: new TestClock(1_755_000_000_000),
      conformance: false,
      json: true,
    });

    expect(result.stdout).not.toContain(ESC);
    // No summary block reached the machine document: no next action, no
    // overall line, no per-state census.
    expect(result.stdout).not.toContain('next:');
    expect(result.stdout).not.toContain('overall:');

    // The same key paths, in the same order, as the committed golden — the
    // fixture path and the shipped path are one renderer.
    const real = new Set(keyPaths(JSON.parse(result.stdout)));
    for (const path of new Set(keyPaths(JSON.parse(golden('doctor.golden.json'))))) {
      expect([...real]).toContain(path);
    }
  }, 60_000);

  it('a real status --json has the golden document, key for key', async () => {
    const dataDir = join(tmp, 'status-data');
    await mkdir(dataDir, { recursive: true });
    await writeFile(
      join(dataDir, 'daemon.json'),
      JSON.stringify({
        pid: 999_999,
        port: 7777,
        token: 'not-a-real-token',
        startedAt: 1_754_812_800_000,
        processStartedAt: 'never',
      }),
    );

    const result = runStatus({
      env: { DeFlow_DATA_DIR: dataDir },
      clock: new TestClock(1_754_812_865_000),
      json: true,
    });

    expect(result.exitCode).toBe(0);
    expect(result.stdout).not.toContain(ESC);
    expect(result.stdout).not.toContain('next:');
    // A stale daemon is a different variant of the same document; the keys the
    // "running" golden pins are the ones a consumer branches on first.
    expect(Object.keys(JSON.parse(result.stdout) as object)[0]).toBe('status');
  });
});

suite('the failure this golden exists to catch (EPIC-18-S62, scenario 2)', () => {
  it('goes red, naming the added lines, when a summary block leaks into the document', () => {
    // A golden nobody has watched go red is a golden nobody can trust. This is
    // the exact regression AC6 is written against: the presentation layer's
    // summary appended to *every* rendered output, `--json` included.
    const leaked = `${golden('doctor.golden.json')}\nnext: run 'deflow doctor --fix'\noverall: fail — 4 ok, 3 warn, 1 fail, 0 skipped\n`;

    expect(leaked).not.toBe(golden('doctor.golden.json'));

    // And it names them: the comparison that goes red is only useful if what
    // it reports is the two lines somebody added, not "the files differ".
    const before = new Set(golden('doctor.golden.json').split('\n'));
    const added = leaked.split('\n').filter((line) => line !== '' && !before.has(line));
    expect(added).toContain("next: run 'deflow doctor --fix'");
    expect(added.some((line) => line.startsWith('overall:'))).toBe(true);

    // The second half of the same regression: the document stops parsing.
    expect(() => JSON.parse(leaked)).toThrow();
  });
});
