/**
 * A recording `git` shim for KAR-07.1's spawn-chokepoint tests
 * (docs/14-testing-strategy.md §3.3's "fake binaries, not mocked modules",
 * applied to git rather than to an agent).
 *
 * It never behaves like real git. It exists for exactly three things this
 * package cannot prove with real git alone: that a forbidden argument shape
 * never reaches a `git` process at all (the log stays empty), that the argv
 * and environment `Git.run()` hands to `execa` are what §1.1 specifies, and
 * that `git --version` can be stubbed to an arbitrary string to drive the
 * version floor without installing a different git on the machine running
 * the suite.
 */
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { delimiter, join } from 'node:path';

export interface FakeGitInvocation {
  /** `argv.join(' ')`, without the leading `git`. */
  readonly argv: string;
  /** The child's `SSH_AUTH_SOCK`, or the empty string if unset. */
  readonly sshAuthSock: string;
}

export interface FakeGitBin {
  /** `PATH` with the shim's directory prepended, so a bare "git" finds it. */
  readonly pathEnv: string;
  /** Every invocation so far, in order. Empty means never invoked. */
  invocations(): Promise<FakeGitInvocation[]>;
}

/** Separates the argv from SSH_AUTH_SOCK on a logged line: a control
 * character (0x01), so it can never collide with a real argument or a real
 * socket path. */
const FIELD_SEP = String.fromCharCode(1);

/**
 * Writes an executable `git` to `<tmp>/fake-git-bin/git`. `--version`
 * anywhere in the args prints `git version <versionOutput>` (default: no
 * output at all, i.e. an unparsable `git --version`) and the process exits
 * `exitCode` (default 0) for every invocation.
 */
export async function writeFakeGit(
  tmp: string,
  options: { readonly versionOutput?: string; readonly exitCode?: number } = {},
): Promise<FakeGitBin> {
  const binDir = join(tmp, 'fake-git-bin');
  await mkdir(binDir, { recursive: true });
  const logFile = join(binDir, 'invocations.log');
  await writeFile(logFile, '');
  const binary = join(binDir, 'git');
  const exitCode = options.exitCode ?? 0;
  const versionLine =
    options.versionOutput === undefined ? '' : `git version ${options.versionOutput}`;

  const script = [
    '#!/bin/sh',
    '# Generated by packages/daemon/test/support/fake-git-bin.ts -- never real git.',
    `printf '%s${FIELD_SEP}%s\\n' "$*" "$SSH_AUTH_SOCK" >> ${shellQuote(logFile)}`,
    'case " $* " in',
    "  *' --version '*|*' --version')",
    `    printf '%s\\n' ${shellQuote(versionLine)}`,
    '    ;;',
    'esac',
    `exit ${exitCode}`,
    '',
  ].join('\n');

  await writeFile(binary, script);
  await chmod(binary, 0o755);

  return {
    pathEnv: `${binDir}${delimiter}${process.env.PATH ?? ''}`,
    async invocations(): Promise<FakeGitInvocation[]> {
      const contents = await readFile(logFile, 'utf8');
      return contents
        .split('\n')
        .filter((line) => line !== '')
        .map((line) => {
          const [argv = '', sshAuthSock = ''] = line.split(FIELD_SEP);
          return { argv, sshAuthSock };
        });
    },
  };
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}
