/**
 * A fake first-party CLI on a real `PATH` — `gh` for KAR-10.1 and KAR-22.4,
 * `acli` for KAR-22.6 (docs/14-testing-strategy.md §3.3's "fake binaries, not
 * mocked modules", applied the way `fake-git-bin.ts` applies it to `git`).
 *
 * **Generalised from `./fake-gh-bin.ts` by KAR-22.6 rather than copied.** The
 * second connector needed the identical fixture for a differently-named binary,
 * and two nearly-identical shell-script generators is exactly the duplication
 * KAR-22.6 exists to avoid — in the specs as much as in the source.
 * `./fake-gh-bin.ts` is now a two-line call into this.
 *
 * It never talks to a network. It answers exactly as scripted, logging every
 * invocation so a spec can assert what was actually run — and, just as
 * importantly, what was *not*.
 *
 * ## `credentialToken` is what makes the ADR-0003 assertion falsifiable
 *
 * A real vendor CLI holds a token in its own credential store. A fake that held
 * nothing would make "DeFlow never captures the token" unfalsifiable — there
 * would be no token to capture. So this fixture writes one into a file beside
 * the binary and lets a spec script a route that prints it. An implementation
 * that decided to cache the credential has an obvious way to obtain it, and the
 * connector specs notice when it does.
 */
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { delimiter, join } from 'node:path';

export interface FakeCliBin {
  /** `PATH` with the shim's directory prepended, so a bare name finds it. */
  readonly pathEnv: string;
  /** Where the fake keeps "its own" credential. DeFlow must never read it. */
  readonly credentialStore: string;
  /** Every `argv.join(' ')` invoked so far, in order. */
  invocations(): Promise<string[]>;
}

/** One scripted answer, chosen by a substring of the joined argv. */
export interface FakeCliRoute {
  /** Matched against `"$*"` — e.g. `'api -i user'`, `'workitem search'`. */
  readonly match: string;
  readonly stdout?: string;
  readonly stderr?: string;
  readonly exitCode?: number;
}

export interface WriteFakeCliOptions {
  /** The fallback answer, for an argv no route matched. Written to stdout, exit 0. */
  readonly stdout?: string;
  /** Written to stderr; exit 1. Mutually exclusive with a 0 `exitCode`. */
  readonly stderr?: string;
  readonly exitCode?: number;
  /** Per-subcommand answers, tried in order before the fallback above. */
  readonly routes?: readonly FakeCliRoute[];
  /** A token to write into the fake's own credential store. */
  readonly credentialToken?: string;
}

/**
 * Writes an executable `<name>` to `<tmp>/fake-<name>-bin/<name>`.
 *
 * Every invocation logs its argv, then takes the first `routes` entry whose
 * `match` appears in the joined argv — or the fallback `stdout`/`stderr`/
 * `exitCode` when none does.
 *
 * Each binary gets its **own** directory, so a spec that needs both a fake `gh`
 * and a fake `acli` prepends two of them and neither shadows the other.
 */
export async function writeFakeCli(
  tmp: string,
  name: string,
  options: WriteFakeCliOptions = {},
): Promise<FakeCliBin> {
  const binDir = join(tmp, `fake-${name}-bin`);
  await mkdir(binDir, { recursive: true });
  const logFile = join(binDir, 'invocations.log');
  await writeFile(logFile, '');
  const binary = join(binDir, name);

  // Deliberately *not* under the daemon's data directory, and deliberately a
  // real file: the token-hunting specs read it back to prove they are searching
  // for something that exists on this machine.
  const credentialStore = join(binDir, 'credential-store.txt');
  await writeFile(
    credentialStore,
    options.credentialToken === undefined
      ? 'no credential\n'
      : `${name}\n  oauth_token: ${options.credentialToken}\n`,
    { mode: 0o600 },
  );

  const exitCode = options.exitCode ?? (options.stderr === undefined ? 0 : 1);
  const stdout = options.stdout ?? '{}';
  const stderr = options.stderr ?? '';

  const answer = (route: Omit<FakeCliRoute, 'match'>): string[] => {
    const code = route.exitCode ?? (route.stderr === undefined ? 0 : 1);
    return [
      route.stdout === undefined || route.stdout === '' ? '' : `printf '%s' ${q(route.stdout)}`,
      route.stderr === undefined || route.stderr === ''
        ? ''
        : `printf '%s' ${q(route.stderr)} 1>&2`,
      `exit ${code}`,
    ].filter((line) => line !== '');
  };

  const cases = (options.routes ?? []).flatMap((route) => [
    `  *${shellPattern(route.match)}*)`,
    ...answer(route).map((line) => `    ${line}`),
    '    ;;',
  ]);

  const script = [
    '#!/bin/sh',
    '# Generated by packages/daemon/test/support/fake-cli-bin.ts -- never a real CLI.',
    `printf '%s\\n' "$*" >> ${q(logFile)}`,
    ...(cases.length === 0
      ? answer({ stdout, stderr, exitCode })
      : [
          'case "$*" in',
          ...cases,
          '  *)',
          ...answer({ stdout, stderr, exitCode }).map((l) => `    ${l}`),
          '    ;;',
          'esac',
        ]),
    '',
  ].join('\n');

  await writeFile(binary, script);
  await chmod(binary, 0o755);

  return {
    pathEnv: `${binDir}${delimiter}${process.env.PATH ?? ''}`,
    credentialStore,
    async invocations(): Promise<string[]> {
      const contents = await readFile(logFile, 'utf8');
      return contents.split('\n').filter((line) => line !== '');
    },
  };
}

/** The directory `writeFakeCli` put `name` in — for composing a two-binary `PATH`. */
export const binDirOf = (bin: FakeCliBin): string => bin.pathEnv.split(delimiter)[0] ?? '';

/** A `PATH` holding every one of `bins`, in order, ahead of the ambient one. */
export const pathWith = (...bins: readonly FakeCliBin[]): string =>
  [...bins.map(binDirOf), process.env.PATH ?? ''].join(delimiter);

function q(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/**
 * `match` as a `case` pattern that matches it **literally**.
 *
 * Single-quoted, because a `case` pattern is subject to word splitting and
 * globbing: an unquoted `*api -i user*` is three words and a syntax error, and
 * an unquoted `*` inside a route would silently match everything.
 */
function shellPattern(match: string): string {
  return q(match);
}
