/**
 * A fake `gh` for KAR-10.1's issue-resolution tests
 * (docs/14-testing-strategy.md §3.3's "fake binaries, not mocked modules",
 * applied to `gh` the way `fake-git-bin.ts` applies it to `git`).
 *
 * It never talks to GitHub. It answers `gh api repos/<owner>/<repo>/issues/<n>`
 * exactly as scripted, logging every invocation so a spec can assert what was
 * actually run without touching a real network.
 */
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { delimiter, join } from 'node:path';

export interface FakeGhBin {
  /** `PATH` with the shim's directory prepended, so a bare "gh" finds it. */
  readonly pathEnv: string;
  /** Every `argv.join(' ')` invoked so far, in order. */
  invocations(): Promise<string[]>;
}

export interface WriteFakeGhOptions {
  /** Written to stdout, exit 0 — a plausible-shaped issue body. */
  readonly stdout?: string;
  /** Written to stderr; exit 1. Mutually exclusive with a 0 `exitCode`. */
  readonly stderr?: string;
  readonly exitCode?: number;
}

/**
 * Writes an executable `gh` to `<tmp>/fake-gh-bin/gh`. Every invocation logs
 * its argv, then prints `stdout` (default `'{}'`) and exits 0, or — when
 * `stderr`/a non-zero `exitCode` is given — prints `stderr` and exits that
 * code instead.
 */
export async function writeFakeGh(
  tmp: string,
  options: WriteFakeGhOptions = {},
): Promise<FakeGhBin> {
  const binDir = join(tmp, 'fake-gh-bin');
  await mkdir(binDir, { recursive: true });
  const logFile = join(binDir, 'invocations.log');
  await writeFile(logFile, '');
  const binary = join(binDir, 'gh');

  const exitCode = options.exitCode ?? (options.stderr === undefined ? 0 : 1);
  const stdout = options.stdout ?? '{}';
  const stderr = options.stderr ?? '';

  const script = [
    '#!/bin/sh',
    '# Generated by packages/daemon/test/support/fake-gh-bin.ts -- never real gh.',
    `printf '%s\\n' "$*" >> ${shellQuote(logFile)}`,
    stdout === '' ? '' : `printf '%s' ${shellQuote(stdout)}`,
    stderr === '' ? '' : `printf '%s' ${shellQuote(stderr)} 1>&2`,
    `exit ${exitCode}`,
    '',
  ]
    .filter((line) => line !== '')
    .join('\n');

  await writeFile(binary, script);
  await chmod(binary, 0o755);

  return {
    pathEnv: `${binDir}${delimiter}${process.env.PATH ?? ''}`,
    async invocations(): Promise<string[]> {
      const contents = await readFile(logFile, 'utf8');
      return contents.split('\n').filter((line) => line !== '');
    },
  };
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}
