/**
 * KAR-19.5 AC4 / EPIC-19-S34 — **a test that cannot go red is worse than no
 * test**, so every link is cut in turn and the smoke test must fail for each.
 *
 * This is the part of the story that matters. A smoke test is a claim about
 * wiring, and the only way to settle a claim about wiring is to unplug
 * something and watch it break. Without this table, KAR-19.5 would be the
 * 2026-08-12 mistake reproduced exactly one level up: a green assertion nobody
 * had ever seen fail.
 *
 * **How a link is cut.** The scenario runs the built binary, so a row copies
 * `packages/cli/dist` and applies exactly one textual edit to the copy — the
 * bundler preserves identifiers and comments, so a call site is a stable
 * anchor. Two properties make that a cut rather than a mutation:
 *
 * - The `find` string must occur **exactly once** across the whole copied
 *   bundle. Zero occurrences means the row's anchor has rotted and the row
 *   fails; two means the edit is ambiguous and the row fails. Either way the
 *   table refuses to report a pass it cannot justify.
 * - The row is checked against the **unsabotaged** binary once, at the top,
 *   by `live-run.test.ts` itself — if the intact chain did not reach a terminal
 *   state, every row below would fail for that reason instead of its own.
 *
 * **The failure must name the link.** S34's last clause — *"it does not fail
 * with a timeout alone"* — is why `runSmokeScenario` waits for each stage by
 * name and throws `SmokeStageMissing` carrying the link. A row asserts both
 * that the scenario failed *and* which link it named, so a cut that broke
 * something else entirely is a red row rather than a quiet pass.
 *
 * Verifies: EPIC-19-S34 · KAR-19.5 AC4 · test plan #2
 */
import { cpSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { afterEach, beforeAll, expect, it, describe as suite } from 'vitest';
import {
  DIST_DIR,
  ensureBuilt,
  LINKS,
  repoRoot,
  runSmokeScenario,
  type SmokeLink,
  SmokeStageMissing,
  SMOKE_STAGE_TIMED_OUT as TIMED_OUT,
} from './support/harness.ts';

beforeAll(() => {
  ensureBuilt();
}, 600_000);

const copies: string[] = [];

/**
 * Always removed, `DeFlow_KEEP_TMP` or not — unlike the scenario's own tmpdir.
 *
 * AC7's keep is for the thing a failure is diagnosed from: the run's data
 * directory, with a ledger you open in `sqlite3`. A sabotaged bundle is not
 * that. It is 6 MB of generated bytes, reproducible exactly from `dist/` plus
 * the row's own `find`/`replace`, and keeping it would leave a near-identical
 * copy of the real binary sitting beside it in the working tree — which CI does
 * set `DeFlow_KEEP_TMP=1` for the whole job, so the exception would be the
 * normal case there rather than the rare one.
 */
afterEach(async () => {
  for (const dir of copies.splice(0)) await rm(dir, { recursive: true, force: true });
});

/** One textual edit. `find` must occur exactly once in the whole bundle. */
interface Cut {
  readonly find: string;
  readonly replace: string;
}

interface Sabotage {
  /** S34's own wording for the link this row removes. */
  readonly row: string;
  /**
   * Every call site that produces this link.
   *
   * Usually one. `the framing wake written at intake` has two, and that is a
   * finding rather than an inconvenience: KAR-19.1 added `rearmFraming`, which
   * re-arms a missing framing wake once a second for any run that is pending
   * framing and has no row. So intake's own `scheduleWake` is **repaired within
   * a tick** if it is removed alone, and a row that cut only it would report a
   * hole in the smoke test that is really a redundancy in the daemon. Cutting a
   * link means cutting the link, not one of its two producers.
   */
  readonly cuts: readonly Cut[];
  /** The stage the smoke test must then name. */
  readonly names: SmokeLink;
  /**
   * KAR-19.9 AC9 — substrings the failure message must also carry.
   *
   * Every row above cuts a link, and the link's *name* is the whole diagnosis:
   * the stage never happened, and which stage it was says why. The row this
   * field exists for is different in kind — nothing is missing, a provider is
   * **failing** — and for that one "the run did not reach `run.created`" is a
   * true sentence that sends the next reader to exactly the wrong place. So
   * that row asserts the ending as well as the link: the run *failed*, and it
   * failed for a reason out of KAR-02.10's closed taxonomy.
   */
  readonly says?: readonly string[];
  /**
   * KAR-19.9 AC9 — *"it does not reach its own timeout"*.
   *
   * A row that fails by waiting out the stage budget tells the next reader
   * nothing about which link broke, which AC4 already calls a hole. This is the
   * inverse clause, and it is the whole point of the row: before this story the
   * failing turn was re-dispatched every 30 s with no ceiling, so the scenario
   * sat here until the budget expired and reported that time had passed.
   *
   * Asserted against the **sentence** rather than against a wall-clock bound,
   * and that is the stronger of the two rather than the cheaper. `stage()` has
   * exactly one arm that gives up on the clock and it says so in words, so its
   * absence is the fact this clause is about, stated exactly. A bound on
   * elapsed time would be measuring a scenario that also runs `DeFlow init`,
   * two `git` invocations and a cold daemon start, and would read a loaded
   * machine as a reintroduced infinite retry.
   */
  readonly notByTimeout?: boolean;
}

/**
 * One row per link in EPIC-19-S34's `Examples` table, in the same order.
 *
 * Each `find` is a call site rather than a declaration: removing the *function*
 * would break the build, and what is under test is whether anything calls it —
 * which is precisely the shape of the defect this epic exists to remove.
 */
const TABLE: readonly Sabotage[] = [
  {
    row: 'the framing wake written at intake',
    cuts: [
      {
        // `intake.ts` — the hand-off written in the same transaction as
        // `task.submitted`.
        find:
          'scheduleWake(ports.db, {\n\t\t\trunId,\n\t\t\tnodeId: FRAMING_NODE,' +
          '\n\t\t\twakeAt: ports.clock.now(),\n\t\t\treason: FRAMING_WAKE_REASON\n\t\t});',
        replace: '',
      },
      {
        // `drive.ts`'s `rearmFraming` — the second producer, see `Sabotage.cuts`.
        find:
          'scheduleWake(ports.db, {\n\t\t\t\trunId,\n\t\t\t\tnodeId: FRAMING_NODE,' +
          '\n\t\t\t\twakeAt: now,\n\t\t\t\treason: FRAMING_WAKE_REASON\n\t\t\t});',
        replace: '',
      },
    ],
    names: LINKS.created,
  },
  {
    row: 'the ticker started by boot()',
    cuts: [
      {
        find: 'const ticker = startTicker({',
        replace: 'const ticker = ((o) => ({ stop: () => {}, wake: () => {} }))({',
      },
    ],
    names: LINKS.created,
  },
  {
    row: 'the call that reaches run.created',
    cuts: [
      {
        find: 'const outcome = await runFramingInterview({',
        replace: 'const outcome = await ((o) => ({ outcome: "suspended" }))({',
      },
    ],
    names: LINKS.created,
  },
  {
    row: 'the call that compiles the plan',
    cuts: [
      {
        find: 'const compiled = await compilePlanV1({',
        replace:
          'const compiled = await ((o) => ({ outcome: "failed", failure: { message: "sabotaged", ' +
          'deflowFailure: { reason: "internal" } } }))({',
      },
    ],
    names: LINKS.proposed,
  },
  {
    row: 'the call that executes the plan',
    cuts: [
      { find: 'await executeRun({\n\t\t\tdb,', replace: 'await ((o) => undefined)({\n\t\t\tdb,' },
    ],
    names: LINKS.started,
  },
  {
    row: 'the io_chunk producer',
    cuts: [
      {
        find: 'appendIo(chunk) {\n\t\t\treturn Promise.resolve(appendIoChunk(db, {',
        replace:
          'appendIo(chunk) {\n\t\t\tif (chunk) return Promise.resolve(0);' +
          '\n\t\t\treturn Promise.resolve(appendIoChunk(db, {',
      },
    ],
    names: LINKS.chunk,
  },
  {
    // KAR-19.9 AC9 / EPIC-19-S64 — not a cut link but a **failing provider**,
    // which is the row the 2026-08-13 afternoon asked for. `renderReturn` is
    // the last step of the bundled agent's structured turn; with it returning
    // nothing the very next line refuses, so the binary exits non-zero with a
    // sentence on stderr and zero bytes on stdout for *every* turn. That is a
    // wedged vendor CLI exactly as DeFlow sees one — a real child's real exit
    // code — and it is the shape of the reported failure.
    //
    // The capability probe is untouched, so the machine still has a working
    // provider and the run is admitted as it would be anywhere. What fails is
    // the turn, which is the distinction KAR-19.2 already covers the other half
    // of.
    row: 'a provider that fails every turn',
    cuts: [
      {
        find: '\tconst document = renderReturn(schemaId, seed, scenario?.returns ?? null);',
        replace: '\tconst document = null;',
      },
    ],
    names: LINKS.created,
    // Named as *failed*, with the typed reason beside it. Before this story
    // there was no reason to name: the daemon retried the identical failure
    // every 30 s and appended nothing, so the run's own ledger could not have
    // produced this sentence and neither could any surface reading it.
    says: ['the run failed', 'agent.nonzero-exit'],
    notByTimeout: true,
  },
];

/** The bundle chunks a sabotage may be applied to. */
const chunksOf = (dir: string): readonly string[] =>
  readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.mjs'))
    .map((entry) => join(dir, entry.name));

/**
 * `dist/` with one link cut, and a refusal when the cut did not apply cleanly.
 *
 * The occurrence count is the row's own integrity check: an anchor that has
 * rotted since it was written would otherwise produce a *green* row — the
 * scenario passing because nothing was actually removed — which is the exact
 * shape of hole this table exists to close.
 */
async function sabotagedDist(row: Sabotage): Promise<string> {
  // Beside `packages/cli/dist` rather than in `os.tmpdir()`, and it is not a
  // preference: the bundle leaves its native dependencies external
  // (better-sqlite3, node-pty), and Node resolves those by walking up to a
  // `node_modules` that has them — which in a pnpm workspace is
  // `packages/cli/node_modules`, not the repository root's. A copy anywhere
  // else exits 1 on `ERR_MODULE_NOT_FOUND` at `DeFlow init`, and every row
  // below would then fail for that reason instead of for the link it cut.
  // `.gitignore` covers the prefix.
  const dir = await mkdtemp(join(repoRoot, 'packages', 'cli', '.smoke-sabotage-'));
  copies.push(dir);
  cpSync(DIST_DIR, dir, { recursive: true });

  for (const cut of row.cuts) {
    let applied = 0;
    for (const chunk of chunksOf(dir)) {
      const source = readFileSync(chunk, 'utf8');
      const occurrences = source.split(cut.find).length - 1;
      if (occurrences === 0) continue;
      applied += occurrences;
      writeFileSync(chunk, source.split(cut.find).join(cut.replace), 'utf8');
    }
    expect(
      applied,
      `the sabotage for "${row.row}" matched ${String(applied)} times in the bundle for ` +
        `${JSON.stringify(cut.find.slice(0, 60))}; it must match exactly once, or the row is ` +
        'asserting nothing about the link it names',
    ).toBe(1);
  }
  return dir;
}

suite('EPIC-19-S34 — every link cut in turn, and the smoke test goes red for each', () => {
  for (const row of TABLE) {
    it(`fails, naming the link, with ${row.row} removed`, { timeout: 180_000 }, async () => {
      const distDir = await sabotagedDist(row);

      // The scenario, against the cut bundle. A stage budget far below the
      // smoke test's own: a cut link is a stage that will never happen, and
      // six rows waiting out the full budget would cost ten minutes to learn
      // nothing.
      const budgetMs = 20_000;
      const began = Date.now();
      const thrown = await runSmokeScenario({ distDir, stageTimeoutMs: budgetMs }).then(
        () => null,
        (error: unknown) => error,
      );
      const tookMs = Date.now() - began;

      expect(
        thrown,
        `the smoke test passed with ${row.row} removed from the shipped path, which means it ` +
          'does not actually assert that link',
      ).not.toBeNull();
      expect(thrown).toBeInstanceOf(SmokeStageMissing);
      expect((thrown as SmokeStageMissing).link).toBe(row.names);
      // S34's last clause: the message names the link rather than only
      // reporting that time ran out.
      const message = (thrown as SmokeStageMissing).message;
      expect(message).toContain(row.names);

      // KAR-19.9 AC9 / EPIC-19-S64 — and, for the row whose provider fails
      // rather than whose link is missing, what the run's own ledger says
      // about the ending.
      for (const phrase of row.says ?? []) expect(message, message).toContain(phrase);

      if (row.notByTimeout === true) {
        expect(
          message,
          `the row for "${row.row}" gave up on the clock after ${String(tookMs)} ms of a ` +
            `${String(budgetMs)} ms stage budget, which is a timeout wearing a failure’s ` +
            'clothes: a run that gave up must end the scenario, not outlast it',
        ).not.toContain(TIMED_OUT);
      }
    });
  }
});
